actionname: 'max-dc-publisher'
description: 'Publish DC using templates'
inputs:
  push-to-boond:
    description: 'Whether to publish to boond'
    required: false
    default: "false"
  files:  # files to publish
    description: 'Files to publish'
    required: true
  slack-notify:
    description: 'The field ID that contains the github username mapping in slack, followed by a = and the github username to look for. If not specified, no mesage will be sent.'
    required: false
    default: false
  globals-file:
    description: 'Globals file to merge data from'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - --files="${{ inputs.files }}"
    - --root="."
    - --output="./dist"
    - --slack-notify="${{ inputs.slack-notify }}"
    - --boond=${{ inputs.push-to-boond }}
    - --globals=${{ inputs.globals-file }}
